### ISSUE TITLE
Package adds an entire second to startup time.

### ISSUE THREAD

**Issue by StevenTang166** [b3by/atom-clock#13] opened 2016-12-31 04:54 UTC
"This package adds 1018ms" to startup time. Seems a little high, when this package only contains a clock. Perhaps their is a fix for this?

**Comment by b3by** [comment] 2016-12-31 10:07
Thank you for reporting this problem. I really want the clock to be as light and fast as possible, so this is important.

Could you please give me some extra details about your configuration? On my machine (MacBook Pro late 2012, Intel core i7), the clock takes less than 5ms for the loading, and around 6-7 ms for the activation.

Anyway, I have an update ready that should speed up the package a bit (`moment.js`, the only package dependency, will be lazily imported). If the problem is consistent, I will roll it out now, but if the problem is just transient I will wait to gather more changes (especially to the specs).

**Comment by StevenTang166** [comment] 2016-12-31 16:03
On second startup it takes 133ms, which is quite a strange change. The problem must be transient. The specs of my device is a Windows 10 64bit Intel i7 4 cores @2GHz.

**Comment by b3by** [comment] 2016-12-31 16:14
Yes, that is weird. It should be better than ~100ms anyway.
I will leave the issue open until the next version rollout, in the meantime I'll investigate and see if I have any issue with the activation time.

**Comment by b3by** [comment] 2017-01-14 14:34
This should be fixed by now. After the latest release, `moment` is lazily imported, which should speed up the loading even further.

**Closed by b3by** 2017-01-14 14:34 UTC
Labels: enhancement
