### ISSUE TITLE
Uncaught Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by alireza-kaviani** [b3by/atom-clock#58] opened 2018-11-09 17:50 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 ia32
**Electron**: 2.0.9
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-clock](https://github.com/b3by/atom-clock) package 0.1.16

### Stack Trace

Uncaught Error: Cannot find module 'moment'

```
At module.js:545

Error: Cannot find module 'moment'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at AtomClockView.getDate (/packages/atom-clock/lib/atom-clock-view.js:115:21)
    at HTMLDivElement.title (/packages/atom-clock/lib/atom-clock-view.js:135:27)
    at u.getTitle (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:2932521)
    at u.hasContent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:2931625)
    at u.show (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:2928370)
    at u.<anonymous> (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:2927746)
```

### Commands

```
     -0:19.2.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-clang 0.11.5 
file-icons 2.1.26 
gcc-make-run 0.2.12 
python-runner 1.2.0 
teletype 0.13.3 
```

**Comment by b3by** [comment] 2018-11-12 19:56
Thank you for opening this. I'll try to replicate the bug, see if I can figure out what's going on there.

**Comment by b3by** [comment] 2019-03-29 17:43
Unfortunately I was not able to reproduce the issue. Since there is no further activity related to it, I'll close it for now.

**Closed by b3by** 2019-03-29 17:43 UTC
